apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - image: rsoprojectwut/paymentservice:1.0.0
          imagePullPolicy: Always
          name: payment-pod
          ports:
            - containerPort: 8080
          env:
            - name: SECRET_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-user-pass
                  key: password
