apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: payment
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
        - image: rsoprojectwut/paymentservice
          imagePullPolicy: IfNotPresent
          name: payment-pod
          env:
            - name: CONSUMER_API_URL
              value: "http://consumer"
          ports:
            - containerPort: 8080
