apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: invoice
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: invoice
    spec:
      containers:
        - image: rsoprojectwut/invoiceservice
          imagePullPolicy: Always
          name: invoice-pod
          ports:
            - containerPort: 8080
