kubectl apply -f testDeploy/testDeploy-deployment.yaml
kubectl apply -f testDeploy/testDeploy-lb.yaml
kubectl apply -f consumerService/consumer-deployment.yaml
kubectl apply -f consumerService/consumer-lb.yaml
kubectl apply -f payment/payment-deployment.yaml
kubectl apply -f payment/payment-lb.yaml
kubectl apply -f invoice/invoice-deployment.yaml
kubectl apply -f invoice/invoice-lb.yaml
kubectl apply -f frontend/frontend.yaml
kubectl apply -f http-gateway.yaml
kubectl apply -f virtualservice-external.yaml