---
apiVersion: v1
kind: Service
metadata:
  name: testdeploy
  labels:
    app: testdeploy
spec:
  type: NodePort
  selector:
    app: testdeploy
  ports:
  - protocol: TCP
    port: 8080
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: testdeploy
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: testdeploy
    spec:
      containers:
      - name: testdeploy
        image: rsoprojectwut/testdeploy:0.0.2
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8025
          initialDelaySeconds: 30
          timeoutSeconds: 1
