apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: consumer
spec:
  replicas: 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: consumer
    spec:
      containers:
        - image: rsoprojectwut/consumerservice:1.0.0
          imagePullPolicy: Always
          name: consumer-pod
          ports:
            - containerPort: 8080
